########################
### YUU Data Academy ###
### Longley Pham     ###
### Exercise 1B      ###
########################

customer_id = 3385                  #Unique identifier, should be a number for base cases, but can be alphanumeric
customer_name = 'James Leroy'       #string; first, last but can be separated
customer_gender = ''                #string, should be select by case
customer_dob = '5/13/2003'          #string if you want to include hyphens and slashes; numeric if separated
dl_number = 'A90234890234'          #numeric with the exception of the first/last placeholder
autopolicy_number = 790252          #can be alphanumeric

self_name = 'Longley'
self_city = 'Chicago'
self_state = 'Illinois'

#a) What is the full list of reserved words that can’t be used for variable names?
#       False	def	if	raise
#       None	del	import	return
#       True	elif	in	try
#       and	else	is	while
#       as	except	lambda	with
#       assert	finally	nonlocal	yield
#       break	for	not
#       class	form	or
#       continue	global	pass
#       are the keywords that cannot be used for variables names since they have predefined
#       meaning and syntaxes

#b) Pick 5 of these words and review the explanation for how it is used as a keyword in
#Python.
#       ^def^ - used to define a function
#       ^lambda^ - used to create an anonymous function
#       ^nonlocal^ - used to refer to variables in the nearest enclosing scope that is not global
#       ^yield^ - used to produce a value from a generator function
#       ^assert^ - used to test if a condition is true, and if not, raise an AssertionError
#       These definitions were auto generated by VS Code's built in autocomplete, 
#       but I have a basic understanding of these keywords and their uses in Python.
